<?php
/**
 * Created by PhpStorm.
 * User: webwerks
 * Date: 24/4/17
 * Time: 5:34 PM
 */

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\ORM\Query;
use Cake\Network\Session;
use Cake\ORM\Entity;
use Cake\Database\Type;
use Cake\Event\Event;

class MasterTable extends Table{

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

    }

    public function beforeSave(Event $event,Entity $entity){
        if($entity->isNew()){
            $session=new Session();
            $entity->created_by=$session->read('Auth.User.id');
        }else{
            $session=new Session();
            $entity->modified_by=$session->read('Auth.User.id');
        }
    }

    public function afterSaveCommit(Event $event,Entity $entity){
        return true;
    }

    public function beforeFind(Event $event,Query $query){
        return true;
    }



}